CREATE TYPE category AS ENUM (
    'Body',
    'Mind',
    'Soul',
    'Other'
);

CREATE TABLE tasks (
  task_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  description TEXT NOT NULL UNIQUE,
  category category 
  );

  