CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    fullname TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    profile_pic TEXT NOT NULL,
    current_task INTEGER
        REFERENCES tasks(task_id) ON DELETE CASCADE NOT NULL,
    do_tasks INTEGER ARRAY,
    done_tasks INTEGER ARRAY
);

